config/routes.rb
HousingAssociation::Application.routes.draw do  

  resources :upload_files

  resources :letter_templates do
    collection do
      get :set
    end
  end

  resources :partnerships do
    collection do
      get :search_by_email
    end
  end

  resources :letters do
    collection do
      get :cunter
      get :printa5
    end
    member do
      get :printa4
      
    end
  end

  resources :member_posts

  resources :members do
    member do
      get :search
    end
  end

  resources :contacts do
    member do
      get :search  
    end
    collection do
      get :preson_names
      get :company_names
      get :reciever_names
    end

  end

  resources :educations

  resources :articles

  resources :pdf_forms

  resources :circulars

  resources :comment_complaints

  resources :complaints do
    member do
      get :send_answer
      get :send_and_display_answer
    end
  end

  resources :pay_limits do
    collection do
      get :search
    end
  end 
  resources :roles

  resources :slides

  resources :send_links

  resources :payments

  devise_for :views
  devise_for :users
  resources :users do
    collection do
      get :new_inspector
      get :new_subadmin
    end
  end

  resources :links

  resources :cooperatives do
    collection do      
      get :select_group      
    end
  end

  resources :messages

  resources :pictures

  resources :informs

  resources :managements
  resources :projects
  resources :pages
  root :to => 'static#index'
  get 'login' => 'users#login'
  get 'search_phone' => 'contacts#search'
  get 'search_member' => 'members#search'

end

app/views/shared/_admin_menu.html.haml
.col-md-6
  = link_to "مدیریت دفترچه تلفن", Contact  
  %br
  = link_to "گزارش گیری از کابران", User
  %br
  = link_to "گزارش گیری درخواست مشارکت", PayLimit
 
  %br
  = link_to  Complaint do
    %p.width80.pull-right= "گزارش داوری"
    %b.notif= Complaint.where(display: false, admin_visited: false).count
    
  %br
  = link_to " مدیریت اخبار و اعلامیه ها", Inform
  %br
  = link_to 'مدیریت اسلایدر', Slide
  %br
  = link_to "مدیریت پروژه ها", Project
  %br
  = link_to " مدیریت بخشنامه ها", Circular
.col-md-6  

  = link_to "مدیریت مطالب آموزشی", Education
  %br
  = link_to "مدیریت مقالات", Article
  %br
  = link_to "مدیریت فرم های اتحادیه", PdfForm
  %br
  = link_to "مدیریت صفحات متنی", Page
  %br
  = link_to "مدیریت پیوندها", Link
  %br
  = link_to "مدیریت مدیران", Management
  %br
  = link_to "مدیریت پیام ها", Message
  %br
  = link_to 'پروفایل مدیر سایت', edit_user_registration_path(current_user)
  %br
  = link_to 'بایگانی و مدیریت نامه ها', Letter
  %br
  = link_to "خروج", destroy_user_session_path, :method => :delete

app/views/shared/_admin_menu_cooperatives.html.haml
.col-md-12
  = link_to "فایل های ارسالی تعاونیها", upload_files_path
  %br
  
  = link_to "لیست تعاونیها ", Cooperative
  %br
  
  = link_to "تعریف تعاونی جدید", new_cooperative_path
  %br
  
  = link_to "نمایش و معرفی اعضا تعاونیها", Member
  %br
  = link_to 'لیست ایمیل های ارسالی به تعاونیها', letters_path(:email_list => "show")
  %br
  
  = link_to "ارسال ایمیل به تعاونیها", new_letter_path(letter_type:"email")
  %br
  
  = link_to "تعریف عنوان پست تعاونی", MemberPost
  %br

app/views/shared/_cooperative_menu.html.haml
    
= link_to 'تکمیل اطلاعات تعاونی', cooperatives_path
%br

= link_to 'مدیریت اعضای تعاونی', members_path(cooperative_id: current_user.cooperative_code)
%br
= link_to 'ارسال فایل', upload_files_path
.clear-float

app/views/shared/_footer.html.haml
.col-lg-8     
  %div
    %iframe{frameborder: "0", height: "350", marginheight: "0", marginwidth: "0", scrolling: "no", src: "https://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=Apadana,+Mashhad,+Khorasan+Razavi,+Iran&aq=0&oq=apada&sll=36.311784,59.569263&sspn=0.021544,0.039482&ie=UTF8&hq=&hnear=Apadana,+Abkuh,+Mashhad,+Khorasan+Razavi,+Iran&t=m&z=14&ll=36.310743,59.571472&output=embed", width: "425"}
    %br/
    %small
      %a{href: "https://maps.google.com/maps?f=q&source=embed&hl=en&geocode=&q=Apadana,+Mashhad,+Khorasan+Razavi,+Iran&aq=0&oq=apada&sll=36.311784,59.569263&sspn=0.021544,0.039482&ie=UTF8&hq=&hnear=Apadana,+Abkuh,+Mashhad,+Khorasan+Razavi,+Iran&t=m&z=14&ll=36.310743,59.571472", style: "color:#0000FF;text-align:left"} View Larger Map
.col-lg-4.footer-link
  %ul.footer-item
    %li
      = link_to 'صفحه نخست', root_path
    %li
      = link_to 'پروژه ها', projects_path
    %li
      = link_to 'تعاونیها', cooperatives_path
  
  
    %li
      = link_to  'ارسال لینک جاری به دوستان', '#', "data-toggle" => "modal", "data-target" => ".bs-example-modal-sm"
    
    %li
      
      آمار سایت
      = Visit.all.count
      بازدید تاکنون
  .modal.fade.bs-example-modal-sm{"aria-hidden" => "true", "aria-labelledby" => "mySmallModalLabel", role: "dialog", tabindex: "-1"}
    .modal-dialog.modal-sm
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
          %h4#myModalLabel.modal-title ارسال لینک جاری به ایمیل دوستان

        .modal-body
          = render 'send_links/form'
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close

app/views/shared/_inspector_menu.html.haml
    
= link_to 'پروفایل بازرس', edit_user_registration_path(current_user)
%br
= link_to  Complaint do
  %p.width50.pull-right= "گزارش شکایات"
  %b.notif= Complaint.where('inspector_visited is null').count

%br

.clear-float

app/views/shared/_login.html.haml
.contact-form
  = render 'devise/sessions/new'

app/views/shared/_msg_form.html.haml
= form_for @message ||= Message.new, :html => {:class => "contact", name: "contactform", :id => "contactform"} do |f|
  - if @message.errors.any?
    .alert.alert-warning 
      %ul
        - @message.errors.each do |attr, msg|
          %li= msg
  
      
  -if flash[:msgsended]        
    .alert.alert-success= flash[:msgsended] 
  
  .col-md-6
    = f.text_field :user_name, :id => "name", placeholder: "نام خود را وارد کنید"    
  .col-md-6
    = f.text_field :phone, :id => "subject", placeholder: " تلفن خود را وارد کنید", :style => "resize:none"
  .col-md-12
    = f.text_field :email, :id => "email", placeholder: "ایمیل خود را وارد کنید"    
  
  .col-md-6.pull-right
    = f.text_area :text, :id => "comments", placeholder: "پیام خود را وارد کنید", :style => "resize:none"
  .col-md-6
    = f.simple_captcha :label => " عبارت امنیتی را در کادر بالا وارد نمایید." 
  .col-md-4
  .col-md-4
    = f.submit 'ارسال پیام', :class=>"mainBtn", :id => "submit"
  .col-md-4
  .clear-float
%br
:javascript  
  
  $(':submit#submit').click(function(e) {
    $(':text#name, :text#email, textarea#comments').each(function() {
      if ($(this).val().length == 0) {
        $(this).css('border', '2px solid red');
        e.preventDefault();
      }
    });
  });

app/views/shared/_nav_bar.html.haml
%ul.menu-first
  - if current_page?(root_path)
    %li.active
      = link_to 'صفحه اصلی' , '#'    
   
    %li
      = link_to 'داوری' , '#service-4'      
    %li
      = link_to 'تعاونی ها' , '#service-2'      
    %li
      = link_to 'اعلامیه ها' , '#inform'        
    %li
      = link_to 'پروژه ها' , '#portfolio'  
    %li
      = link_to 'مدیران' , '#our-team'    
    %li
      = link_to 'ارتباط با ما' , '#contact'
      
  - else    
  
    %li{:class => ('active' if current_page?(root_path))} 
      = link_to "صفحه اصلی", root_path      
    %li{:class => ('active' if current_page?(educations_path))}
      = link_to 'آموزش', Education
    %li{:class => ('active' if current_page?(complaints_path))}
      = link_to 'داوری', Complaint
    %li{:class => ('active' if current_page?(cooperatives_path))}
      = link_to 'تعاونی ها', Cooperative
    %li{:class => ('active' if current_page?(informs_path))}
      = link_to 'اعلامیه ها' , Inform         
    %li{:class => ('active' if current_page?(projects_path))}
      = link_to "پروژه ها", Project
    %li
      = link_to 'ارتباط با ما' , root_path

app/views/shared/_upload_image_form.html.haml
.form-group.upload-pic      
  = picture.file_field :image
  -if picture.object.image.present?
    = image_tag picture.object.image(:medium) , :class => "enable_file_select" 

  .form-group
    = picture.label "توضیحات عکس", :class => "col-sm-3 control-label" 
    = picture.text_area :description, :rows => 2, :style => "resize:none"  
    = picture.label "برای حذف این کادر روی آیکن سطل آشغال مقابل کلیک کنید.", :class => "control-label" 
    = picture.link_to_remove (image_tag ("Delete_Icon.png"), :class => "recyclebin-icon"), :class => "remove-task col-sm-3"
.clear-float
%hr

app/views/shared/_user_menu.html.haml
.admin-title
  %h3= "خوش آمدید"
  %h5
    = current_user.name
    = current_user.last_name
.list-group
  
  = link_to "مدیریت پروفایل شخصی", edit_user_registration_path(current_user), :class => "list-group-item"  
  .list-group-item  
    %b= 'پروژه های مشارکتی'
    %br
    - @pro_user = PayLimit.where( { user_id:  current_user.id })      
    -if @pro_user.present?
      - @pro_user.each do |up|
        = link_to up.project.title, project_path(up.project.title)
        %br
    -else
      %p= 'شما در هیچ پروژه ای شرکت نکرده اید.'
  
  