config/routes.rb
HousingAssociation::Application.routes.draw do  

  resources :upload_files

  resources :letter_templates do
    collection do
      get :set
    end
  end

  resources :partnerships do
    collection do
      get :search_by_email
    end
  end

  resources :letters do
    collection do
      get :cunter
      get :printa5
    end
    member do
      get :printa4
      
    end
  end

  resources :member_posts

  resources :members do
    member do
      get :search
    end
  end

  resources :contacts do
    member do
      get :search  
    end
    collection do
      get :preson_names
      get :company_names
      get :reciever_names
    end

  end

  resources :educations

  resources :articles

  resources :pdf_forms

  resources :circulars

  resources :comment_complaints

  resources :complaints do
    member do
      get :send_answer
      get :send_and_display_answer
    end
  end

  resources :pay_limits do
    collection do
      get :search
    end
  end 
  resources :roles

  resources :slides

  resources :send_links

  resources :payments

  devise_for :views
  devise_for :users
  resources :users do
    collection do
      get :new_inspector
      get :new_subadmin
    end
  end

  resources :links

  resources :cooperatives do
    collection do      
      get :select_group      
    end
  end

  resources :messages

  resources :pictures

  resources :informs

  resources :managements
  resources :projects
  resources :pages
  root :to => 'static#index'
  get 'login' => 'users#login'
  get 'search_phone' => 'contacts#search'
  get 'search_member' => 'members#search'

end

app/models/partnership.rb
# encoding: UTF-8
class Partnership < ActiveRecord::Base
  extend PersianNumbers
  persian_dates :birthdate
  has_many :pay_limits
  validates :first_name, :last_name, :email, :father_name, :mobile, :presence => {:message => 'فیلد های ستاره دار را پر کنید'}
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => 'ایمیل نامعتبر است.' } 
  validates :email, :uniqueness => {:message => 'ایمیل در سیستم وجود دارد'}
  validates :mobile, format: { with: /\d{10}/, message: "لطفا ده رقم شماره تلفن همراه خود را بدون صفر وارد کنید." }
  
  def self.search(email)   
    search_condition = "%" + email + "%"  
    find(:all, :conditions => ['email LIKE :s', :s => search_condition])
  end
end

app/controllers/partnerships_controller.rb
# encoding: UTF-8
class PartnershipsController < ApplicationController
  before_action :set_partnership, only: [:show, :edit, :update, :destroy]

  # GET /partnerships
  # GET /partnerships.json
  def index
    @partnerships = Partnership.all
  end

  # GET /partnerships/1
  # GET /partnerships/1.json
  def show
  end
  
  def search_by_email
    email = params[:email]   
    if email
      @find_email = Partnership.search(email)
    end 
  end

  # GET /partnerships/new
  def new
    @partnership = Partnership.new
    @project_id = params[:project_id]
  end

  # GET /partnerships/1/edit
  def edit
  end

  # POST /partnerships
  # POST /partnerships.json
  def create
    @partnership = Partnership.new(partnership_params)    
    p '----------------'
    @project_id = params[:project_id]
    
    if @partnership.save     
      redirect_to new_pay_limit_path(:partnership_id => @partnership.id, :project_id => @project_id)
      flash[:reg]= 'اطلاعات شخصی شما ثبت شد' 
    else
      render action: 'new'
      flash[:error] = 'خطا در ثبت اطلاعات شخصی'
    end
  
  end

  # PATCH/PUT /partnerships/1
  # PATCH/PUT /partnerships/1.json
  def update
    respond_to do |format|
      if @partnership.update(partnership_params)
        format.html { redirect_to @partnership, notice: 'Partnership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @partnership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partnerships/1
  # DELETE /partnerships/1.json
  def destroy
    @partnership.destroy
    respond_to do |format|
      format.html { redirect_to partnerships_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partnership
      @partnership = Partnership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partnership_params
      params.require(:partnership).permit( :first_name, :last_name, :email, :father_name, :birthdate, :gender, :phone_number, :mobile, :farhangi, :address, :description)
    end
end

app/helpers/partnerships_helper.rb
module PartnershipsHelper
end

app/views/partnerships/_email_search_result.html.haml
- if @find_email.present?
  .info-cadre
    - @find_email.each do |partnership|
      .pull-right.width50
        %h3= 'اطلاعات فردی'
        %p  
          %b نام و نام خانوادگی:
          = partnership.first_name + " " + partnership.last_name
        %p
          %b نام پدر:
          = partnership.father_name
        %p
          %b ایمیل:
          = partnership.email
      .pull-right.width50
        %h3= 'اطلاعات مشارکتی'
        - partnership.pay_limits.each do |pay_limit|
          .info-pay_limits
            %p
              %b عنوان پروژه:
              = pay_limit.project.title
            %p
              %b تاریخ ثبت درخواست:
              =JalaliDate.new(pay_limit.created_at) 
            %p
              %b سقف مبلغ پرداختی:
              = pay_limit.amount
            %p
              %b سایر توضیحات:
              = pay_limit.description
          .info-pay_limits{:style => "background:#E6E6FA"}
            %h3= 'نتیجه درخواست'
            %p
              - if pay_limit.accept
                %b این درخواست تایید شده است. 
                %i برای هماهنگی های بعدی با شما تماس گرفته خواهد شد.
              - else
                %b درخواست شما در حال بررسی است
                
            %p
              %b سایر توضیحات:
              = pay_limit.accept_description
      .clear-float

app/views/partnerships/_form.html.haml
= form_for @partnership ||= Partnership.new, {:style => "direction:rtl"} do |f|
  - if @partnership.errors.any?
    #error_explanation      
      %ul
        - @partnership.errors.each do |attr, msg|
          %li= msg

  =hidden_field_tag :project_id, @project_id
  .form-group.col-sm-3.pull-right
    = f.label 'نام:*', :class => "control-label"
    = f.text_field :first_name, :class => "form-control", :id => "first_name"
  .form-group.col-sm-3.pull-right
    = f.label 'نام خانوادگی:*', :class => "control-label"
    = f.text_field :last_name, :class => "form-control", :id => "last_name"
  .form-group.col-sm-3.pull-right
    = f.label 'ایمیل:*', :class => "control-label"
    = f.text_field :email, :class => "form-control", :id => "email"
  .form-group.col-sm-3.pull-right
    = f.label 'نام پدر:*', :class => "control-label"
    = f.text_field :father_name, :class => "form-control", :id => "father_name"    
  .form-group.col-sm-3.pull-right
    = f.label 'شماره تماس ثابت:', :class => "control-label"
    = f.text_field :phone_number, :class => "form-control"
  .form-group.col-sm-3.pull-right
    = f.label 'شماره تماس همراه:*', :class => "control-label"
    = f.text_field :mobile, :class => "form-control", :id => "mobile"
  .form-group.col-sm-3.pull-right
    = f.label 'تاریخ تولد:', :class => "control-label"
    = f.text_field :birthdate_fa, :class => "fa_date form-control"
  
  .form-group.col-sm-3.pull-right
    = f.label 'جنسیت:', :class => "control-label"
    =  f.select(:gender, [['مذکر',1], ['مونث',0]])  
  .clear-float
  .form-group.col-sm-6.pull-right
    .col-sm-8= f.label 'عضو خانواده فرهنگیان هستم.', :class => "control-label"
    .col-sm-2= f.check_box :farhangi
  .clear-float
  .form-group.col-sm-6.pull-right
    = f.label 'آدرس', :class => "control-label"
    = f.text_area :address, :class => "form-control", :style => "resize:none"
  .form-group.col-sm-6.pull-right
    = f.label 'سایر توضیحات:', :class => "control-label"
    = f.text_area :description, :class => "form-control", :style => "resize:none"  
  .clear-float
  .col-sm-4
    = link_to 'بازگشت', :back
  .form-group.col-sm-4
    = f.submit 'مرحله بعد', :class => "mainBtn partnership-hide", :id => "partnership-submit"
    
    
    
:javascript  
  
  $(':submit#partnership-submit').click(function(e) {
    $(':text#first_name, :text#last_name, :text#email, :text#father_name, :text#mobile').each(function() {
      if ($(this).val().length == 0) {
        $(this).css('border', '2px solid red');
        e.preventDefault();
      }
    });
  });

app/views/partnerships/_search_by_email.html.haml
= form_tag search_by_email_partnerships_path, :method => "get", id: "email-form", :remote => "true" do 
  = text_field_tag :email, params[:email], :id => 'email_field', placeholder: 'ایمیل خود را وارد کنید' 
  = submit_tag "جستجو", :name => nil, :id => "email-submit" 
  #email-clear.col-md-4= link_to  "تصحیح", '#code'            
  .clear-float
  

:javascript
  $('#email-clear').click(function()
  {
    $('#email_field').val('');    
  });
  
  $(':submit#email-submit').click(function(e) {
    $(':text#email_field').each(function() {
      if ($(this).val().length == 0) {
        $(this).css('border', '2px solid red');
        e.preventDefault();
      }
    });
  });

app/views/partnerships/edit.html.haml
%h1 Editing partnership

= render 'form'

= link_to 'Show', @partnership
\|
= link_to 'Back', partnerships_path

app/views/partnerships/index.html.haml
%h1 Listing partnerships

%table
  %tr
    
    %th First name
    %th Last name
    %th Email
    %th Father name
    %th Birthdate
    %th Gender
    %th Phone number
    %th Mobile
    %th Farhangi
    %th
    %th
    %th

  - @partnerships.each do |partnership|
    %tr
      
      %td= partnership.first_name
      %td= partnership.last_name
      %td= partnership.email
      %td= partnership.father_name
      %td= partnership.birthdate
      %td= partnership.gender
      %td= partnership.phone_number
      %td= partnership.mobile
      %td= partnership.farhangi
      %td= link_to 'Show', partnership
      %td= link_to 'Edit', edit_partnership_path(partnership)
      %td= link_to 'Destroy', partnership, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Partnership', new_partnership_path

app/views/partnerships/new.html.haml
.width80.set-center.margin-top
  .tbox2
    .title  
      - if @project.present?
        %h1= "فرم ثبت نام در پروژه" + " " + @project.title
      -else
        %h1= "فرم ثبت نام در پروژه"
      %h2= 'وارد کردن اطلاعات شخصی'
    .col-sm-1
    .col-sm-11
      .step.col-sm-3
        %p= 'مرحله سوم'
        %p= 'دریافت کد رهگیری'
      .step.col-sm-3
        %p= 'مرحله دوم'
        %p= 'تکمیل اطلاعات مالی'
      .step.active.col-sm-3
        %p= 'مرحله اول'
        %p= 'تکمیل اطلاعات شخصی'
      
      
    .contact-form.col-sm-12{:style => "direction:rtl"}
      -if flash[:error]        
        .alert.alert-warning= flash[:error]
      = render 'form'
    

app/views/partnerships/search_by_email.js.haml
-if @find_email.present? 
  $('#pay-limit-search-result').empty();
  $("#pay-limit-search-result").prepend("#{escape_javascript(render(:partial => 'email_search_result', :locals => {:result => @contact }))}");        
  $('form#email-form [type="text"]').val('');
  $('form#code-form [type="text"]').val('');
- else
  %h1= 'ایمیل وجود ندارد'
  

app/views/partnerships/show.html.haml
%p#notice= notice

%p
  %b Tracking code:
  = @partnership.tracking_code
%p
  %b First name:
  = @partnership.first_name
%p
  %b Last name:
  = @partnership.last_name
%p
  %b Email:
  = @partnership.email
%p
  %b Father name:
  = @partnership.father_name
%p
  %b Birthdate:
  = @partnership.birthdate
%p
  %b Gender:
  = @partnership.gender
%p
  %b Phone number:
  = @partnership.phone_number
%p
  %b Mobile:
  = @partnership.mobile
%p
  %b Farhangi:
  = @partnership.farhangi

= link_to 'Edit', edit_partnership_path(@partnership)
\|
= link_to 'Back', partnerships_path