config/routes.rb
HousingAssociation::Application.routes.draw do  

  resources :upload_files

  resources :letter_templates do
    collection do
      get :set
    end
  end

  resources :partnerships do
    collection do
      get :search_by_email
    end
  end

  resources :letters do
    collection do
      get :cunter
      get :printa5
    end
    member do
      get :printa4
      
    end
  end

  resources :member_posts

  resources :members do
    member do
      get :search
    end
  end

  resources :contacts do
    member do
      get :search  
    end
    collection do
      get :preson_names
      get :company_names
      get :reciever_names
    end

  end

  resources :educations

  resources :articles

  resources :pdf_forms

  resources :circulars

  resources :comment_complaints

  resources :complaints do
    member do
      get :send_answer
      get :send_and_display_answer
    end
  end

  resources :pay_limits do
    collection do
      get :search
    end
  end 
  resources :roles

  resources :slides

  resources :send_links

  resources :payments

  devise_for :views
  devise_for :users
  resources :users do
    collection do
      get :new_inspector
      get :new_subadmin
    end
  end

  resources :links

  resources :cooperatives do
    collection do      
      get :select_group      
    end
  end

  resources :messages

  resources :pictures

  resources :informs

  resources :managements
  resources :projects
  resources :pages
  root :to => 'static#index'
  get 'login' => 'users#login'
  get 'search_phone' => 'contacts#search'
  get 'search_member' => 'members#search'

end

app/models/project.rb
# encoding: UTF-8
class Project < ActiveRecord::Base
  extend FriendlyId  
  friendly_id :title
  
  is_impressionable
  has_many :circulars
  has_many :pictures
  has_many :informs
  has_many :pay_limits
  accepts_nested_attributes_for :pictures, reject_if: :all_blank, allow_destroy: true
  has_and_belongs_to_many :users, :class_name => "User", :join_table => "projects_users", :foreign_key => "project_id" 
end

app/controllers/projects_controller.rb
# encoding: UTF-8
class ProjectsController < ApplicationController
  impressionist :actions=>[:show,:index]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :check_autentication, only: [:new, :edit]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.order(" created_at desc")
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    impressionist(@project, "message...") # 2nd argument is optional
    if current_user
      @member_id = current_user.id    
      @reg_before = PayLimit.where( {user_id: @member_id , project_id:  @project.id })      
      @pro_informs = Inform.where( { project_id:  @project.id })      
    end
  end

  # GET /projects
  def new
    @project = Project.new
    
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
   
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'پروژه جدید ایجاد شد. ' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'تغییر اطلاعات انجام شد.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :address, :description, :Area, :unit, :Status, 
            :land_area, :floor, :block , :start_year, :finish_year,
            pictures_attributes: [:image, :description, :_destroy, :_update]          
            )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= nested_form_for @project, :html => { :multipart => true  } do |f|
  - if @project.errors.any?
    #error_explanation
      %ul
        - @project.errors.each do |attr, msg|
          %li= msg

  .form-group
    = f.label  "عنوان پروژه", :class => "control-label"
    = f.text_field :title,  :class => "control-label"
  
  .form-group
    = f.label "متراژ زمین:", :class => "control-label"
    = f.text_field :land_area,  :class => "control-label"
  .form-group
    = f.label "متراژ هر واحد:", :class => "control-label"
    = f.text_field :Area,  :class => "control-label"
  .form-group
    = f.label "تعداد واحد:", :class => "control-label"
    = f.number_field :unit,  :class => "control-label"
  .form-group
    = f.label "تعداد طبقات:", :class => "control-label"
    = f.number_field :floor,  :class => "control-label"
  .form-group
    = f.label "تعداد بلوک:", :class => "control-label"
    = f.number_field :block,  :class => "control-label"
  .form-group
    = f.label "سال شروع ساخت:", :class => "control-label"
    = f.number_field :start_year,  :class => "control-label"
  .form-group
    = f.label "سال تحویل:", :class => "control-label"
    = f.number_field :finish_year,  :class => "control-label"
  .form-group
    .col-md-1
      = f.check_box :Status,  :class => "control-label"
    = f.label "اگر پروژه تحویل داده شده است تیک مقابل را فعال کنید:", :class => "control-label"
  .form-group
    = f.label " آدرس", :class => "control-label"
    = f.text_area :address,  :class => "control-label", :style => "resize:none"
  .form-group
    = f.label "توضیحات", :class => "control-label"
    = f.text_area :description,  :class => "control-label", :style => "resize:none"
    
    
  .form-group
    = f.fields_for :pictures do |picture|  
      = render "shared/upload_image_form", :picture => picture
  
  .form-group
    = f.label "برای افزودن تصاویر برای این پروژه دکمه زیر را فشار دهید و در کادری که نمایش داده می شود تصویر مورد نظر را انتخاب کنید:", :class => "control-label"
    = f.label "دقت داشته باشید حجم هر عکس باید کمتر از ۵۰۰کیلوبایت باشد.", :class => "control-label", :style=> "color:#ec523f"
    = f.link_to_add content_tag(:span, "افزودن تصویر"), :pictures, :id => "add_new_picture", :class => "save-btn"
  .form-group
    = f.submit 'ثبت', :class => "mainBtn"
    
    
:javascript
  function enable_file_select(){
    $(".enable_file_select").unbind('click').click(function(){
      $(this).parent().find("input:file").click();
    });
   }

  enable_file_select();

  $("#add_new_picture").click(function(){
    $(".enable_file_select").unbind('click');
    window.setTimeout('enable_file_select()', 1000);
  });

app/views/projects/edit.html.haml
.width80.set-center.margin-top
  .tbox2
    .title
      %h1= ' ویرایش اطلاعات پروژه' + ' ' + @project.title
    .contact-form.width50
      = render 'form'

    = link_to 'بازگشت', projects_path

app/views/projects/index.html.haml
.width80.set-center.margin-top
  .tbox2
    .title
      %h1= "لیست پروژه ها"
    - if is_admin?
      = link_to 'پروژه جدید', new_project_path, :class => "save-btn"
    .col-md-4.col-sm-6.pay-limit-box
      = link_to 'درخواست مشارکت در پروژه', new_partnership_path
    .clear-float
    .index-projects
      - @projects.each do |project|
        .projects-holder         
          .top-div
            = link_to project do
              %h3.pro-title-holder= project.title
            - if is_admin?
              = link_to 'ویرایش', edit_project_path(project)
              = link_to 'حذف', project, :method => :delete, :data => { :confirm => 'آیا مطمئن هستید؟' }
          .sample-pic.set-center.col-lg-4{:id => 'project-'+project.id.to_s}
            = image_tag project.pictures.first.image(:small), :class => "set-center"           
            
          .col-lg-6
            %p= project.description
            %p
              -if project.Status        
                %i= 'تحویل داده شده'                
              -else
                %i= 'در دست احداث'    
        .clear-float
        .col-sm-2
          .more
            = link_to 'مشاهده بیشتر', project   
              
        .clear-float
      
      .clear-float
    

   

app/views/projects/new.html.haml
.width80.set-center.margin-top
  .tbox2
    .title
      %h1 معرفی پروژه جدید
    .contact-form.width50
      = render 'form'
    
    = link_to 'بازگشت', projects_path

app/views/projects/show.html.haml
.width80.set-center.margin-top
  .tbox2    
    
    .title
      %h1= 'پروژه ' +  @project.title     
       
      -if is_admin?           
        = link_to 'ویرایش', edit_project_path(@project)
        \|
        = link_to 'بازگشت', projects_path
        
    %div
      %i= 'تعداد بازدید '
      = @project.impressionist_count 
      نفر   
      .row.text-center 
        
      
        .col-md-5.info
          %p
            %b وضعیت:
            -if  @project.Status
              تحویل داده شده
            -else
              در دست احداث
          %hr
          %p
            %b متراژ زمین:
            = @project.land_area
          %p
            %b متراژ هر واحد:
            = @project.Area
          %p
            %b تعداد طبقات:
            = @project.floor
          %p
            %b تعداد واحد:
            = @project.unit
          %p
            %b تعداد بلوک:
            = @project.block
          %p
            %b آدرس:
            = @project.address
          %p
            %b توضیحات تکمیلی:
            = @project.description
          %p
            %b سال شروع ساخت:
            = @project.start_year
          %p
            %b سال تحویل:
            = @project.finish_year
        .col-md-6 
          =link_to (image_tag @project.pictures.first.image(:medium)), @project.pictures.first.image(:original), :class => "group2 cboxElement", :title => @project.title
        - unless @project.Status
          .col-md-4.col-sm-6.pay-limit-box
            = link_to 'ثبت نام در پروژه ', new_partnership_path(:project_id => @project.id)
          
        
      .clear-float
      
      .sub-title 
        %h3.col-md-2= 'اطلاعیه ها'
        .col-md-9.line-orange 
        
        .clear-float
        -if @pro_informs.present?
          - @pro_informs.each do |inform|
            %div
              %p
                %b 
                  = inform.title          
              %p    
                = raw inform.text
      
      .pic-project
        - @project.pictures.offset(1).each do |picture|
          .col-lg-3.image-project

            =link_to (image_tag picture.image(:small)), picture.image(:original), :data => { :colorbox => true }  , :id => "image-"+picture.id.to_s, :title => picture.project.title , :class => "color_box"    
            %p= picture.description
            -if is_admin?           
              = link_to 'ویرایش', edit_picture_path(picture)
              \|
              = link_to 'حذف', picture, :method => :delete, :data => { :confirm => 'آیا مطمئن هستید؟' }
              
                    
:javascript
  
  $(".color_box").colorbox();
  