config/routes.rb
HousingAssociation::Application.routes.draw do  

  resources :upload_files

  resources :letter_templates do
    collection do
      get :set
    end
  end

  resources :partnerships do
    collection do
      get :search_by_email
    end
  end

  resources :letters do
    collection do
      get :cunter
      get :printa5
    end
    member do
      get :printa4
      
    end
  end

  resources :member_posts

  resources :members do
    member do
      get :search
    end
  end

  resources :contacts do
    member do
      get :search  
    end
    collection do
      get :preson_names
      get :company_names
      get :reciever_names
    end

  end

  resources :educations

  resources :articles

  resources :pdf_forms

  resources :circulars

  resources :comment_complaints

  resources :complaints do
    member do
      get :send_answer
      get :send_and_display_answer
    end
  end

  resources :pay_limits do
    collection do
      get :search
    end
  end 
  resources :roles

  resources :slides

  resources :send_links

  resources :payments

  devise_for :views
  devise_for :users
  resources :users do
    collection do
      get :new_inspector
      get :new_subadmin
    end
  end

  resources :links

  resources :cooperatives do
    collection do      
      get :select_group      
    end
  end

  resources :messages

  resources :pictures

  resources :informs

  resources :managements
  resources :projects
  resources :pages
  root :to => 'static#index'
  get 'login' => 'users#login'
  get 'search_phone' => 'contacts#search'
  get 'search_member' => 'members#search'

end

app/models/letter.rb
#encoding: utf-8
class Letter < ActiveRecord::Base

  # extend FriendlyId  
  #friendly_id :summary

  extend PersianNumbers
  persian_dates :sent_date, :received_date

  LetterTypes = {sent:"صادره", recieved:"وارده", email: "ارسال ایمیل گروهی"}
  belongs_to :sender, class_name:"Contact", :foreign_key => "sender_id"
  has_and_belongs_to_many :recievers , class_name:"Contact"
  
  has_attached_file :scan_file,
                    :url  => "/assets/circulars/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/circulars/:id/:style/:basename.:extension"
  validates_attachment_content_type :scan_file,
      :content_type => [ 'application/pdf' ],
      :message => "نوع فایل نامعتبر است. فقط فایل پی دی اف مجاز است."
  #def senderpreson_name
  #  self.sender.try(:preson_name) 
  #end
  #def senderpreson_name=(senderperson_name)
  #  senderperson_name.strip!
  #  self.sender = Contact.where(preson_name:senderperson_name).first || Contact.create(preson_name:senderperson_name)
  #end

  #def sendercompany_name
   # self.sender.try(:preson_name) 
  #end
  #def sendercompany_name=(sendercompany_name)
   # sendercompany_name.strip!
   # self.sender = Contact.where(company_name:sendercompany_name).first || Contact.create(company_name:sendercompany_name)
  #end

  def reciever_tokens=(ids)
    self.reciever_ids = ids.split(',')
  end
  def reciever_tokens
  end
end

app/controllers/letters_controller.rb
# encoding: UTF-8
class LettersController < ApplicationController  
  
  before_action :set_letter, only: [:show, :edit, :update, :destroy, :printa4]
  before_filter :check_autentication
  respond_to :xls, :html
  PAPERSIZE = 0
  
  # GET /letters
  # GET /letters.json
  def index
    #@letters = Letter.all(include:"sender")
    if params[:email_list].present?      
      @except_mail = Letter.where(letter_type: "email")
    else
      @except_mail = Letter.where.not(letter_type: "email")
    end
    @letters = @except_mail.order(" created_at desc")
    filename = "اندیکاتور-" + Date.today.to_s
    respond_to do |format|
      format.html
      format.xlsx { render xlsx: :index, filename: filename}
    end
  end

  # GET /letters/1
  # GET /letters/1.json
  
   
  def show
    
  end

  # GET /letters/new
  def new
    letter_type = params["letter_type"] || Letter::LetterTypes[:sent]
    
    @letter_type_show = params[:letter_type] 
    @letter = Letter.new(letter_type:letter_type)
    @current_date = JalaliDate.new(Date.today)
    @current_year = JalaliDate.new(Date.today).strftime("%y")
    if Letter.last.present?
      p @last_letter = Letter.maximum(:letter_number)
      
       @last_letter_split = @last_letter.split('/').first
      
       @last_letter_split = @last_letter_split.to_i
       @last_letter_split = @last_letter_split + 1
       @last_letter_split = @last_letter_split.to_s
      
    else
      @last_letter_split = 100
    end
  end
  def cunter
    c = params[:cunter]    
    if Letter.last.letter_number >= c
      p @permission_error = 'شماره وارد شده مجاز نمی باشد.'
    else
      p @start_count = c
    end
  end
  def printa4
    p '-------papersizeA4----------'
    p $papersize = 1
    respond_to do |format|
      format.html do
        render 'printa4.html',  :layout => 'a4size.html'
      end
    end
  end
  def printa5
    p '-------papersizeA5----------'
    p $papersize = 2
    
    #respond_to do |format|
     # format.html do
      #  render 'printa5.html',  :layout => 'a5size.html'
      #end
    #end
  end

  # GET /letters/1/edit
  def edit
    

    p @letter_type_show = params[:letter_type] 
    @pdf_destroy= params[:pdf_destroy]
    if @pdf_destroy.present?
      @letter.update_attribute(:scan_file, nil)
      render action: 'show'
    end

  end

  # POST /letters
  # POST /letters.json
  def create
    @letter = Letter.new(letter_params)
     @current_year = params[:current_year]
     @alphabet = params[:alphabet] 
     @counter_number = params[:counter_number]
     @type_of_letter = params[:type_of_letter]
    if @counter_number && @alphabet && @current_year
      @letter_number =   @counter_number +  '/' + @alphabet + '/' +@current_year
      @letter.letter_number = @letter_number
    end
    if @letter.letter_type == 'recieved'
      @addcontact = Contact.new(preson_name: @letter.senderpreson_name, company_name: @letter.sendercompany_name)
      @addcontact.save!
      p '----Add To Contact-----'
    
    end
    
    if @letter.save
      redirect_to @letter
      flash[:letter] = 'نامه در سیستم ثبت شد' 
      
      if params[:letter_type_email]  == 'email'
        if params[:send_all] == 'send_to_all'
          
          @cooperative = Contact.where.not('cooperative_id' => nil)
           @recievers = @cooperative.map { |x| x[:id] }          
          @letter.update_attribute(:reciever_ids, @recievers.collect )
          UserMailer.send_group_mail(@letter).deliver      
        end
      end
      
    else
      render action: 'new'      
    end
  
  end

  # PATCH/PUT /letters/1
  # PATCH/PUT /letters/1.json
  def update
    
    if @letter.update(letter_params)
      redirect_to @letter
      flash[:editletter] =  'ویرایش انجام شد.' 
      @type_of_letter = params[:type_of_letter]
    else
      render action: 'new' 
    end
    
  end

  # DELETE /letters/1
  # DELETE /letters/1.json
  def destroy
    @letter.destroy
    respond_to do |format|
      format.html { redirect_to letters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_letter
      @letter = Letter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def letter_params
      params.require(:letter).permit(:letter_type, :summary, :sent_date_fa, :received_date_fa,
       :senderpreson_name, :sendercompany_name, :content, :attachment, :reciever_ids, :reciever_tokens,
       :letter_number, :scan_file, :received_letter_number, :ehteramn)
    end
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/letters/_form.html.haml
#letter_cunter{:style => "width:30%; float:right; background:#8BC4D6 " }
  %b تغییر شمارنده نامه
  = form_tag cunter_letters_path, :method => "get", id: "cunter-form", :remote => true do 
    = text_field_tag :cunter, params[:cunter], :id => 'cunter_field' , placeholder: "عدد شروع کننده شمارنده را وارد نمایید."
    = submit_tag "ثبت", :name => nil, :id => "cunter-submit" , :style => "width:30%; float:right " 
    #cunter-clear.col-md-4= link_to  "تصحیح", '#phone'
    #cunter-close.col-md-4= link_to  "بستن", '#close'
.clear-float
-#
  #add_reciever{:style => "position:absolute; left:0; bottom:-10%"}
    = form_tag new_contact_path, :method => "put", id: "search-form", :remote => true do 
      = text_field_tag :add_reciever, params[:add_reciever], :id => 'add_reciever_field', placeholder: 'نام دریافت کننده جدید را اضافه کنید'
      %button.save-btn#search-submit= 'send'
      #clear.col-md-4= link_to  "تصحیح", '#phone'
    #search_result.search_result
= form_for @letter do |f|
  - if @letter.errors.any?
    #error_explanation      
      %ul
        - @letter.errors.each do |attr, msg|
          %li= msg
  
  
  .col-sm-12.andicator

    .col-sm-5
      #change-letter-cunter.btn.btn-info تغییر شمارنده نامه   

      = f.hidden_field :letter_type, :value => @letter_type_show
      .form-group.dates
        = f.label 'شماره نامه:', :class => "control-label ", :style => "width:30%; float:right; " 
        .col-sm-9 
          - if @letter.letter_number.present?
            %b= @letter.letter_number
          - else
            - if @last_letter.present?
              %b#counter-number{:style => "width:20%; float:right "}=  @last_letter_split 
              
              = hidden_field_tag :counter_number, params[:counter_number], :id => 'counter_number_field', :value => @last_letter_split
            - else
              %b#counter-number{:style => "width:20%; float:right "}= 101
              = hidden_field_tag :counter_number, params[:counter_number], :id => 'counter_number_field'
            
            = hidden_field_tag :type_of_letter, params[:type_of_letter], :id => 'type_of_letter_field' , :value => ( @letter_type_show == 'sent'  ? '۱' : '۲')
            = hidden_field_tag :letter_type_email, params[:letter_type_email], :id => 'type_of_letter_field' , :value => ('email' if @letter_type_show == 'email')

            %b{:style => "width:20%; float:right "}=  '/' + @current_year  + '/'
            
            = hidden_field_tag :current_year, params[:current_year], :id => 'current_year_field' , :value => @current_year

            %select#region_3{name: "alphabet", :style => "width:30%; float:right; "}
              %option{value: "د"} د
              %option{selected: "selected", value: "الف"} الف
              

      .clear-float  
      - if @letter.blank?
        #change-letter-cunter
          %i= 'برای تغییر عدد شروع کننده شمارنده نامه '
          = link_to 'اینجا کلیک کنید.', '#'
        
      .clear-float  
        - if @letter.letter_type == 'sent' || @letter.letter_type == 'email'
          - if @letter.present?
            .form-group.dates
              = f.label 'تاریخ ارسال:', :class => "control-label ", :style => "width:30%; float:right "    
              %b= @letter.sent_date_fa
          - else
            .form-group.dates
              = f.label 'تاریخ ارسال:', :class => "control-label ", :style => "width:30%; float:right "    
              = f.text_field :sent_date_fa, class:" fa_date form-control", :value => @current_date, :style=> "width:50%; "            
        - elsif @letter.letter_type == 'recieved'
          .form-group.dates
            = f.label 'تاریخ دریافت:', :class => "control-label", :style => "width:30%; float:right "        
            = f.text_field :received_date_fa, class:"fa_date form-control", :style => "width:50%; " 
        
      
        
    .col-sm-3.besella
      %b= 'بسمه تعالی'
    .col-sm-4
      %h1.letter-title-new= 'اتحادیه تعاونیهای مسکن فرهنگیان استان خراسان شماره ثبت ۱۱۹۰۵'
        
        
      
  .clear-float
  .base-letter
    .form-group
      - if @letter_type_show == 'ایمیل'        
        = f.label 'موضوع نامه:', :class => "control-label"    
      - else
        = f.label 'خلاصه نامه:', :class => "control-label"    
      = f.text_field :summary, :class => "form-control"
    
    .col-sm-12
      - if @letter.letter_type == 'recieved'
        .form-group.col-sm-6.pull-right
          = f.label 'شخص ارسال کننده:', :class => "control-label"    
          - if @letter.senderpreson_name.present?
            = f.text_field :senderpreson_name
          - else  
            = f.text_field :senderpreson_name, data: {autocomplete_source: preson_names_contacts_path, load: @letter.recievers.map{|c|{id:c.id, name:c.preson_name}}}, :class => "form-control"
        .form-group.col-sm-6.pull-right
          = f.label 'شرکت ارسال کننده', :class => "control-label"    
          = f.text_field :sendercompany_name, data: {autocomplete_source: company_names_contacts_path, load: @letter.recievers.map{|c|{id:c.id, name:c.preson_name}}}, :class => "form-control"
        .form-group.col-sm-6.pull-right  
          = f.label 'شماره نامه ثبت شده در نامه وارده', :class => "control-label"    
          = f.text_field :received_letter_number
        .clear-float
      - elsif @letter.letter_type == 'sent' 
        .form-group.width50.pull-right
          =f.label 'دریافت کننده:', :class => "control-label" 
          - if @letter.reciever_tokens.present?
            %b= @letter.reciever_tokens
          =f.text_field :reciever_tokens, data: {autocomplete_source: reciever_names_contacts_path, load: @letter.recievers.map{|c|{id:c.id, name:c.preson_name}}}
        .form-group.width50.pull-right
          = link_to "افزودن دریافت کننده جدید", new_contact_path, :class => "save-btn", :id => "add-reciever", :target => "_blank"
      
      - elsif @letter.letter_type == 'email'        
        .form-group.width80
          %span.width30.pull-right= check_box_tag 'send_all', 'send_to_all', :checked => true
          %span= 'جهت ارسال برای تمام تعاونیها تیک مقابل را فعال کنید.'
        
      - else 
        %h2 nothing
          
        
        .clear-float
    .col-sm-3
    - if @letter.letter_type == 'recieved'  
      .col-sm-9      
        .form-group
          = f.label 'ضمیمه فایل نامه وارده', :class => "control-label"    
          %p{:style => "color:red"} قالب فایل pdf مجاز است.
          = f.file_field :scan_file, :class => "ckeditor"
          - if @letter.scan_file.present?
            = image_tag 'get-pdf.png'
            %b= @letter.scan_file_file_name  
    - else
      .col-sm-9 
        .form-group
          = f.label 'رونوشت:', :class => "control-label"    
          = f.text_area :attachment, :class => "ckeditor"
          
      .clear-float
      .form-group
        %i= 'از قالب های آماده استفاده کنید'      
        =select_tag :set_template, options_for_select(LetterTemplate.all.collect{ |lt| [lt.name, lt.id] }), prompt: "قالب نامه موردنظر را انتخاب کنید"
        %br
        %i= 'می توانید برای سهولت ثبت نامه، برای نامه هایی که قالب یکسان دارند. قالب را یک بار تعریف کنید و به دفعات از آن استفاده کنید'
        =link_to "قالب آماده بسازید", new_letter_template_path, target:"_blank", :class => "save-btn"
        
      .clear-float
      .form-group
        = f.label 'عنوان در جایگاه (احترما):', :class => "control-label"    
        = f.text_field :ehteramn, :class => "form-control", :value => 'احتراما'
      .form-group
        = f.label 'محتوی:', :class => "control-label"    
        = f.text_area :content, :class => "ckeditor"
  .clear-float
  .maskan-address.set-center
    %div= 'آدرس: بلوار سازمان آب-نبش آپادانا-پلاک۷-تلفن و فاکس:۳۷۶۲۰۷۵۵-۰۵۱'
  .form-group.col-sm-3
    = f.submit 'ثبت نامه', :class => "mainBtn"  

:coffeescript
  $('#set_template').change ->
    if $('#set_template').val() != ""
      $.ajax({
      url: '#{set_letter_templates_path}',
      data: id: $('#set_template').val(),
      });  

:javascript
  $('#change-letter-cunter').click(function(){
    alert ('آیا مطمئن هستید؟');
    $('#letter_cunter').fadeIn(1000);
  });

  $('#cunter-clear').click(function()
  {
    $('#cunter_field').val('');    
  }); 
  $('#cunter-close').click(function()
  {
    $('#letter_cunter').hide();
  }); 

  
  $(':submit#cunter-submit').click(function(e) {
    $(':text#cunter_field').each(function() {
      if ($(this).val().length == 0) {
        $(this).css('border', '2px solid red');
        e.preventDefault();
      }
    });
  });


        

app/views/letters/_recieve_form.html.haml
.clear-float
= form_for @Rletter=Letter.new do |f|
  - if @Rletter.errors.any?
    #error_explanation      
      %ul
        - @Rletter.errors.each do |attr, msg|
          %li= msg
  .col-sm-12.andicator
    .col-sm-5
      = f.hidden_field :letter_type, :value => 'sent'
      .form-group.dates
        = f.label 'شماره نامه:', :class => "control-label ", :style => "width:30%; float:right; " 
        %b= answer_letter.letter_number
        = f.hidden_field :letter_number, :value => answer_letter.letter_number
        .col-sm-9 
          
      .clear-float  
        .form-group.dates
          = f.label 'تاریخ ارسال:', :class => "control-label ", :style => "width:30%; float:right "    
          = f.text_field :sent_date_fa, class:" fa_date form-control", :value => JalaliDate.new(Date.today), :style=> "width:50%; "            
        
    .col-sm-3.besella
      %b= 'بسمه تعالی'
    .col-sm-4
      %h1.letter-title-new= 'اتحادیه تعاونیهای مسکن فرهنگیان استان خراسان شماره ثبت ۱۱۹۰۵'
  .clear-float
  .base-letter
    .form-group
      - if @letter_type_show == 'ایمیل'        
        = f.label 'موضوع نامه:', :class => "control-label"    
      - else
        = f.label 'خلاصه نامه:', :class => "control-label"    
      = f.text_field :summary, :class => "form-control"
    
    .col-sm-12          
      .col-sm-7.pull-right
        =f.label 'دریافت کننده:', :class => "control-label"         
        - @c = Contact.where("company_name = ?", answer_letter.sendercompany_name).first
        - if @c
          %b= @c.preson_name
          \|
          %b= @c.company_name
          =f.hidden_field :reciever_ids, :value => @c.id
        - else
          .alert.alert-danger= 'دریافت کننده در لیست موجود نیست. لطفا آن را اضافه کنید.'
      .col-sm-5.pull-right
        .form-group.width50.pull-right
          = link_to "افزودن دریافت کننده جدید", new_contact_path, :class => "save-btn", :id => "add-reciever", :target => "_blank"
      .clear-float    
    .col-sm-9 
      .form-group
        = f.label 'رونوشت:', :class => "control-label"    
        = f.text_area :attachment, :class => "ckeditor"
    .clear-float
    .form-group
      %i= 'از قالب های آماده استفاده کنید'      
      =select_tag :set_template, options_for_select(LetterTemplate.all.collect{ |lt| [lt.name, lt.id] }), prompt: "قالب نامه موردنظر را انتخاب کنید"
      %br
      %i= 'می توانید برای سهولت ثبت نامه، برای نامه هایی که قالب یکسان دارند. قالب را یک بار تعریف کنید و به دفعات از آن استفاده کنید'
      =link_to "قالب آماده بسازید", new_letter_template_path, target:"_blank", :class => "save-btn"
      
    .clear-float
    .form-group
      = f.label 'عنوان در جایگاه (احترما):', :class => "control-label"    
      = f.text_field :ehteramn, :class => "form-control", :value => 'احتراما'
    .form-group
      = f.label 'محتوی:', :class => "control-label"    
      = f.text_area :content, :class => "ckeditor"
  .clear-float
  .maskan-address.set-center
    %div= 'آدرس: بلوار سازمان آب-نبش آپادانا-پلاک۷-تلفن و فاکس:۳۷۶۲۰۷۵۵-۰۵۱'
  .form-group.col-sm-3
    = f.submit 'ثبت پاسخ نامه', :class => "mainBtn"  

:coffeescript
  $('#set_template').change ->
    if $('#set_template').val() != ""
      $.ajax({
      url: '#{set_letter_templates_path}',
      data: id: $('#set_template').val(),
      });  

:javascript
  
  $(':submit#cunter-submit').click(function(e) {
    $(':text#cunter_field').each(function() {
      if ($(this).val().length == 0) {
        $(this).css('border', '2px solid red');
        e.preventDefault();
      }
    });
  });


        

app/views/letters/_set_counter_number.html.haml
%b#counter-number{:style => "width:20%; float:right "}= start_count

app/views/letters/cunter.js.haml
-if @start_count.present?  
  $("#counter-number").replaceWith("#{escape_javascript(render(:partial => 'set_counter_number', :locals => {:start_count => @start_count }))}");        
  $('form#cunter-form [type="text"]').val('');
  $('#counter_number_field').val(#{@start_count});   
  $('#letter_cunter').hide();
  
- else @permission_error.present?
  alert('#{@permission_error}');

app/views/letters/edit.html.haml
.width80.set-center.margin-top
  .tbox2
    .title      
      %h1        
        - @letter_type_sym= Letter::LetterTypes[@letter.letter_type.to_sym]
        - if @letter_type_show == 'email'
          = @letter_type_sym
        - else
          ویرایش نامه
          = @letter_type_sym
          
      
    .contact-form
      = render 'form'

    = link_to 'بازگشت', :back

app/views/letters/index.html.haml
.width80.set-center.margin-top
  .page-title-holder
    .title
      %h1 لیست نامه ها
      = link_to 'ثبت نامه صادره', new_letter_path(letter_type:"sent"), :class => "save-btn"
      = link_to 'ثبت نامه وارده', new_letter_path(letter_type:"recieved"), :class => "save-btn"
      = link_to "ارسال ایمیل به تعاونیها", new_letter_path(letter_type:"email"), :class => "save-btn"
      .width30.pull-right
        = link_to  letters_url(format: "xlsx") do
          = image_tag 'excel.png'
          %p= 'دریافت فایل اکسل اندیکاتور'
      .clear-float
  .col-sm-12{:style => "min-height:600px; margin-bottom:5%; padding:0;"}
    .col-sm-6.well{:style => "min-height:400px; border-right:2px solid #4D4D4D; padding:0;"}
      .title
        %h1 نامه های صادره
        %hr
      %table.table.table-striped{id:"sent_letters_table"}
        %thead
          %tr
            %th ردیف‍
            %th شماره نامه 
            %th خلاصه نامه
            %th تاریخ ارسال
            %th دریافت کننده
            - if is_admin?
              %th عملیات
        %tbody{:id => "letter_container"}
          - @letters.each_with_index do |letter, i|      
            - if letter.letter_type.present? && letter.letter_type == 'sent'
              %tr
                %td= (i+1)
                %td= letter.letter_number

                %td= letter.summary
                %td= JalaliDate.new(letter.created_at)  
                
                %td
                  = letter.recievers.collect(&:preson_name).join(',')
                  = letter.recievers.collect(&:company_name).join(',')
                        
                - if is_admin?
                  %td         
                    = link_to 'مشاهده', letter                    
                    = link_to 'ویرایش', edit_letter_path(letter, :letter_type => letter.letter_type)
    
    .col-sm-6.well{:style => "background:#FDFDC5;  padding:0;"}
      .title
        %h1 نامه های وارده
        %hr
      %table.table.table-striped{id:"recieved_letters_table"}
        %thead
          %tr
            %th ردیف‍
            %th شماره نامه          
            %th خلاصه نامه    
            %th تاریخ دریافت
            %th ارسال کننده          
            
            - if is_admin?
              %th عملیات
        
        
          %tbody
            - @recieved_letter = Letter.where(letter_type: 'recieved')
            - @recieved_letter.each_with_index do |letter, i|      
              
              %tr
                %td= (i+1)
                %td= letter.letter_number
                %td= letter.summary
                %td= letter.received_date_fa
                %td 
                  =letter.senderpreson_name
                  =letter.sendercompany_name
                - if is_admin?
                  %td 
                    = link_to 'مشاهده', letter 
                    = link_to 'ویرایش', edit_letter_path(letter, :letter_type => letter.letter_type)

:coffeescript
  window.reloadDataTable = ->
    if !!window.oTable
      window.oTable.fnDestroy(); 
    window.oTable = $("#sent_letters_table").dataTable aoColumnDefs: [
      bSearchable: false
      aTargets: [0,5]
    ,  
      bSortable: false
      aTargets: [0,5]
    ],  oLanguage:
      sSearch: "جستجو:"
      sLengthMenu: "نمایش _MENU_ ردیف"
      sInfo: "جمع ردیفها _TOTAL_ ردیف (_START_ از _END_)"
      sZeroRecords: "هیچ داده ای وجود ندارد"
      sInfoEmpty: "هیچ موردی یافت نشد"
      sInfoFiltered: " - از بین _MAX_ داده موجود"
      oPaginate:
        sPrevious: "صفحه قبلی"
        sNext: "صفحه بعدی"
    window.oTable = $("#recieved_letters_table").dataTable aoColumnDefs: [
      bSearchable: false
      aTargets: [0,5]
    ,  
      bSortable: false
      aTargets: [0,5]
    ],  oLanguage:
      sSearch: "جستجو:"
      sLengthMenu: "نمایش _MENU_ ردیف"
      sInfo: "جمع ردیفها _TOTAL_ ردیف (_START_ از _END_)"
      sZeroRecords: "هیچ داده ای وجود ندارد"
      sInfoEmpty: "هیچ موردی یافت نشد"
      sInfoFiltered: " - از بین _MAX_ داده موجود"
      oPaginate:
        sPrevious: "صفحه قبلی"
        sNext: "صفحه بعدی"

  window.reloadDataTable()

    

app/views/letters/new.html.haml
.width80.set-center.margin-top
  .tbox2
    .title      
      %h1        
        - @letter_type_sym= Letter::LetterTypes[@letter.letter_type.to_sym]
        - if @letter_type_show == 'email'
          = @letter_type_sym
        - else
          ثبت نامه
          = @letter_type_sym
          
      
    .contact-form
      
      = render 'form'

    = link_to 'بازگشت', :back
:javascript
  $('#change-counter').click(function(){
    $('#letter_cunter').show(100);
  });

app/views/letters/printa4.js.haml
var mywindow = window.open('', 'my div', 'height=400,width=600');
mywindow.document.write('<link rel="stylesheet" href="corea4.css" type="text/css" />');
alert('پرینت نامه با سایز A4');
mywindow.document.close();
mywindow.print();
mywindow.close();

app/views/letters/printa5.js.haml
alert('پرینت نامه با سایز A5')
window.print();